### ISSUE TITLE
Date Picker not displaying on Post an Event page

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#704] opened 2020-02-06 22:55 UTC
**Describe the bug**
On the Post an Event page, organizers need to fill in the date of their event using the Date Picker. However, the Date Picker is not displaying, and if they type in the date instead, they get an error message and cannot post their event.

**To Reproduce**
1. Log in to earlyyearsbc.ca with an organizer or admin account
2. Click on "Post an Event"
3. Under "When", click the date fields (From... to...)
4. See that no Date Picker displays
5. Type in dates and click "Post Event" at bottom of page.
6. See Date Picker error message.

**Expected behavior**
When the user clicks the Date field, the Date Picker calendar pops up.

**Screenshots**
Date fields on Post an Event page:
![image](https://user-images.githubusercontent.com/44710357/73985434-02876500-48f0-11ea-8fc3-d698dcb07122.png)

**Additional context**
Related to recent WordPress update?

Also @dshaykewich and @alex-418 please let us know if this sort of error report should go in JIRA instead of GitHub. :)

**Comment by paulagaube** [comment] 2020-02-10 22:56
@dshaykewich  and @alex-418 I'd like to escalate this issue as BUG please, as we've had another complaint from someone who is trying to submit an event on EarlyYearsBC.ca and is unable to do so. 

I tested this afternoon on eypd.bccampus.ca and my test event cannot be submitted without the date picker. I tried manually entering dates in to a new event and this did not work. Here is a screenshot of the error message:

<img width="575" alt="2019-02Feb-10-DatePicker-Missing-EYPD" src="https://user-images.githubusercontent.com/26391359/74197926-32e34200-4c15-11ea-9eb0-a4ce0c6bbcfd.png">

**Comment by paulagaube** [comment] 2020-02-10 23:14
There has been a third report of this problem, which means I will add an FAQ on the Early Years site explaining that this is a known issue and we our technical team is working on a solution.

**Comment by alex-418** [comment] 2020-02-10 23:15
Thanks @paulagaube i'm looking into it now.

**Comment by alex-418** [comment] 2020-02-11 04:39
@paulagaube @dshaykewich I've narrowed in on the cause. There's a front-end dependency that Events Manager requires which needs to be updated (jQuery ui), this is out of sync because we programmatically replaced the plugin version of this in our themes functions.php file with an older version via yarn(package manager) via our themes package.json. Currently yum fails to run on our server (used to install server dependencies) because the Mirror List API which it uses to install these dependencies no longer exists(end of life). To resolve this, we likely have to update other things on the server such as php (It's currently at 7 and End of life) plus the toolchain including yum, yarn, node before we can proceed with updating jQuery. Because once we change the jQuery version we have to build it via yarn build:production.... I'm trying to find a work-around, but it seems that yarn is tied only to the Jenkins user as I can't run it as root or with my account (I've reached out to George about this) but it's a good idea to tackle these maintenance tasks either way. Will let you know once this is resolved.

![iceberg](https://user-images.githubusercontent.com/17072191/74211603-7c4b8580-4c45-11ea-8480-de13a6c72e41.gif)

**Comment by alex-418** [comment] 2020-02-12 21:01
@paulagaube @dshaykewich This is now resolved, I created a test event and the date picker is now working as expected.

**Comment by paulagaube** [comment] 2020-02-12 21:11
Thanks, @alex-418 You are the BEST!!
I have confirmed the date picker now works on earlyyearsbc.ca. 
Woot woot.

**Comment by kkilbey** [comment] 2020-02-13 20:39
Hi @alex-418 - unfortunately the Date Picker has stopped working again! Two people have reported that it was working for them yesterday, and now is not. I just tested in Chrome, and I don't see the Date Picker appear on the "Post an Event" page.

**Comment by alex-418** [comment] 2020-02-13 20:42
@kkilbey How curious, the change I made yesterday was reverted. I suspect some sort of auto-update happened. It's now fixed again, but will keep this open until I discover the cause and prevent it from reverting again.

**Comment by kkilbey** [comment] 2020-02-13 20:49
@alex-418 Super strange! But thanks for fixing so quickly! I will let people know to try posting again now.

**Comment by alex-418** [comment] 2020-02-14 08:15
@kkilbey This should be resolved, please re-open if you encounter this issue again.

**Closed as completed by alex-418** 2020-02-14 08:15 UTC
