### ISSUE TITLE
All posts by this author - Error page

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#650] opened 2019-02-14 20:06 UTC
**Describe the bug**
On an Event page, you can click on the organizer's profile picture to see "all posts by this author." However, if the organizer does not have any blog posts, you are brought to a page that says "Darn it...nothing found" (see screenshots below). This looks like an error message and may be confusing for users.

**To Reproduce**
1. Go to an event on earlyyearsbc.ca (e.g., [Basic Sign Language](https://earlyyearsbc.ca/events/basic-sign-language-2/), posted by Langley CCRR).
2. Hover over the organizer profile picture to the left of the event title; see "all posts by this author" text.
3. Click on the organizer profile picture.
4. See "Darn it...nothing found" error screen.

**Expected behavior**
To be discussed.
@kathreenriel would you like to change the functionality of this button? Perhaps we could link an organizer's profile picture to all of their posted events, rather than their blog posts?

**Screenshots**
Langley CCRR organizer profile picture:
![image](https://user-images.githubusercontent.com/44710357/52813698-361e0f00-304f-11e9-82f5-d02f953b8bae.png)

URL and error screen when profile picture clicked:
![image](https://user-images.githubusercontent.com/44710357/52813764-5a79eb80-304f-11e9-8349-4bcf080c3f67.png)
![image](https://user-images.githubusercontent.com/44710357/52813773-5fd73600-304f-11e9-8545-e6e2788c62b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 72.0.3626.109 (Official Build) (64-bit)

**Additional context**
The organizer profile picture seems to link to blog posts, so if the organizer has created blog posts, the error screen does not appear. For instance, when I select Kathreen's profile picture...
![image](https://user-images.githubusercontent.com/44710357/52814313-aed19b00-3050-11e9-87aa-b02e1ae6a4f9.png)

...I am taken to a list of her blog posts:
![image](https://user-images.githubusercontent.com/44710357/52814069-13d8c100-3050-11e9-8f6d-ad425fe5f86f.png)

**Comment by alex-418** [comment] 2019-05-14 17:03
We're not able to easily modify the events manager page, so we decided to provide copy for the error page

**Comment by kathreenriel** [comment] 2019-05-14 19:35
@paulagaube @kkilbey How about the two statements below instead of the error message?

**Member profile information is not available.** 

Back to [homepage](earlyyearsbc.ca)

**Comment by paulagaube** [comment] 2019-05-14 21:15
@kathreenriel I like the words you've chosen, however, I wonder if this is a specific error page or is it a generic 404 page that will appear whenever a page isn't found? @alex-418 can you clarify please? Do we want the message on this page to be specific or more generic?

**Comment by alex-418** [comment] 2019-05-16 18:17
Completed via https://github.com/BCcampus/eypd/commit/562352826ef7c3b814c465ac6f06af6d0711dcf3

Here's an event en cert, click on the users image to see the new message:
https://eypd.bccampus.ca/events/sign-language-for-early-childhood-educators-part-3/

**Comment by kkilbey** [comment] 2019-05-16 21:14
Looks good! This is working as expected for me.
@paulagaube @kathreenriel would either of you like to validate as well? Ok to move to "Done on Cert"?

**Comment by kathreenriel** [comment] 2019-05-16 23:38
I checked this as well. Great!

**Comment by kathreenriel** [comment] 2019-05-24 18:18
@paulagaube I'm still getting a "Darn It" page. How about you?

**Comment by alex-418** [comment] 2019-05-24 18:21
@kathreenriel Works for me ... here's the direct link https://eypd.bccampus.ca/author/kelsey-kilbey/

**Comment by kathreenriel** [comment] 2019-05-24 18:28
@alex-418 on Prod. there is still the "Darn it" error message

**Comment by alex-418** [comment] 2019-05-24 18:39
@kathreenriel Interesting, I can see the change made it over to prod. Not sure why it's behaving differently, must be a setting or something that's different. The author.php template file is being ignored for some reason.

**Comment by paulagaube** [comment] 2019-05-24 18:47
I still see the Darn it message on Prod too.

**Comment by paulagaube** [comment] 2019-05-24 18:49
This page works as expected: https://earlyyearsbc.ca/author/paula-gaube/

**Comment by paulagaube** [comment] 2019-05-24 18:52
oh, but FYI, if I enter a fake name, the Darn it message appears. Which is perhaps expected behaviour? 
https://earlyyearsbc.ca/author/fake-user/

**Comment by alex-418** [comment] 2019-05-24 19:21
It must have been in the browser's cache, glad it's fixed. @paulagaube Yes, because it's a page that doesn't exist.

**Comment by kathreenriel** [comment] 2019-05-24 19:23
No I don't think it's fixed. I cleared my cache on Chrome and Safari...still when I click on the user's icon I get the Darn it page

**Comment by kathreenriel** [comment] 2019-05-24 19:24
Yep, checked it again...still get the darn it page when I click on the Organizers icon as described by Kelsey in the description at the top

**Comment by paulagaube** [comment] 2019-05-24 19:33
Oh yes, you are right, @kathreenriel , clicking the avatar/icon yields a Darn it message.

**Comment by alex-418** [comment] 2019-05-24 22:26
@kathreenriel can you please provide the link you're checking?

**Comment by kathreenriel** [comment] 2019-05-31 19:57
@alex-418 https://earlyyearsbc.ca/author/michelle/

**Comment by dshaykewich** [comment] 2019-08-06 18:01
Verified that on Prod, Darn it! shows (whether I'm logged in  or not).

Preferred solution: remove link from the user icon (if possible/not too time consuming)

**Comment by alex-418** [comment] 2019-08-13 16:55
@alex-418  to ensure https://github.com/BCcampus/eypd/commit/562352826ef7c3b814c465ac6f06af6d0711dcf3 made it over to prod. If it's there and not working, instead remove the user icon via css.

**Comment by alex-418** [comment] 2019-08-20 20:45
Resolved via https://github.com/BCcampus/eypd/commit/8883cd5f767143a3f40b220d399889437b68b463 the user avatar that links to the error page is now gone.

**Comment by paulagaube** [comment] 2019-08-21 23:45
I confirm that this has been fixed on CERT. 

It does still show up on Prod, perhaps as expected, @alex-418

**Comment by alex-418** [comment] 2019-08-21 23:54
@paulagaube That is correct, thank you for confirming this.

**Closed** 2019-08-23 21:26 UTC
Labels: Epic: Support Engagement With Pro.D Opportunities, Epic: Support Quality, SMALL - 1
