### ISSUE TITLE
Optimize images, convert into WebP format

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#269] opened 2017-10-30 17:29 UTC
Look into php-magick/WebP on jenkins server to ensure images are being optimized, and get them converted into [WebP](https://developers.google.com/speed/webp/) format automatically.

**Comment by alexpflores** [comment] 2017-10-30 17:29
<img width="777" alt="optimize" src="https://user-images.githubusercontent.com/17072191/32185704-3c0b986c-bd5d-11e7-85e0-7f4fcdff5a05.png">

**Comment by bdolor** [comment] 2017-11-01 17:46
* A potential plugin for converting images uploaded by content owners: https://wordpress.org/plugins/shortpixel-image-optimiser/
* A potential Adobe plugin for @RH-BCcampus http://telegraphics.com.au/sw/#webpformat
* Precompiled utilities for developers https://developers.google.com/speed/webp/docs/precompiled (best scenario is if webkit/npm would do the conversion on build)

**Comment by bdolor** [comment] 2017-11-01 18:58
The shortpixel plugin has a limitation of 100 images/per month, then you pay.

**Comment by bdolor** [comment] 2017-11-01 20:08
@kathreenriel - all images that the theme is responsible for have been converted to webp. There are two images in the footer controlled by widgets. I have modified them on eypd and allowed for the uploading of webp images. When these changes move to prod, uploading and changing the footer images is a task that will have to be done.

**Comment by kathreenriel** [comment] 2017-11-01 23:45
![logos](https://user-images.githubusercontent.com/16693738/32303145-045c195a-bf24-11e7-93b9-1a0590cc6ec2.png)
The BC and EYPD logos are missing

**Comment by alexpflores** [comment] 2017-11-01 23:47
Interesting, can't reproduce this on my end. Can you please clear mobile browsers cache, if that doesn't do the trick, please let us know the browser and operating system on your mobile device.

**Comment by kathreenriel** [comment] 2017-11-01 23:52
Cleared my Safari browser and it still shows now images. Just viewed it on Chrome - no images there either. iPhone SE

**Comment by kathreenriel** [comment] 2017-11-01 23:53
IOS 11.1

**Comment by alexpflores** [comment] 2017-11-02 00:03
Thank you, also seeing this on my end now in Safari. Looks like we need to provide a graceful fallback for browsers that don't support it (iOS mainly). 
 
![safari](https://user-images.githubusercontent.com/17072191/32303466-fed8d1a6-bf25-11e7-8472-ef419bf4a521.png)

**Comment by alexpflores** [comment] 2017-11-02 23:34
Once #288 is merged, it'll also take care of the login page logo image. It's now also using webp format and works in safari with fallback. (see screenshot from safari on my local) 

![login_safar](https://user-images.githubusercontent.com/17072191/32355412-b4ad3b00-bfeb-11e7-8c8c-da0bc1672e0d.png)

**Comment by RH-BCcampus** [comment] 2017-11-08 17:10
I see your comments here but it doesn't appear you need anything from me at this time. Let me know.

**Closed** 2018-10-23 19:46 UTC
Labels: BIG - 7, Performance
