### ISSUE TITLE
Lazy-loading JS

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#275] opened 2017-10-30 18:19 UTC
Find the best way to lazyJS. Consider using an IntersectionObserver to intelligently determine when to lazy-load JS.

**Comment by bdolor** [comment] 2017-10-30 21:18
*lazy loading*
- webpack: https://webpack.js.org/guides/lazy-loading/ 
- wordpress: https://webpack.js.org/guides/lazy-loading/
- packagist: https://packagist.org/?q=lazyload%20wordpress&p=0

**Comment by alexpflores** [comment] 2017-10-31 18:14
The above only relates to lazy-loading images, looking into Asynchronous JavaScript to achieve desired results.

**Comment by bdolor** [comment] 2017-10-31 18:22
async is different than lazy (on-demand). The first (webpack) link is `js` related.

**Comment by alexpflores** [comment] 2017-11-02 17:36
Spent too much time here; moving onto another task. I'm not 100% clear on what specific audit score in performance this improves, or what's needed to make that improvement. (First Paint?)  
Thanks @bdolor for finding  Google's implementation of this for WordPress [here](https://github.com/GoogleChromeLabs/ProgressiveWordPress/blob/master/src/theme/scripts/lazyload.js).

**Comment by alexpflores** [comment] 2017-11-15 20:18
After a Deep dive into the murky waters of JS script loading (there's a lot of mixed information online) I can say with confidence that Asynchronous Script loading, Non-blocking Script loading, Lazy Loading Scripts... All mean the same thing for our purposes. Making this a duplicate of #271 because that adds the async attribute.  

It all refers to a Script Loading Pattern to make your scripts/resources load Asynchronously in a Non-Blocking way, which can be Lazy-Loaded if you have multiple scripts. Although this is not recommended for critical scripts/resources, as inlining them is the [recommended way](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources). 

 __Please note:__ Although Asynchronous and Non-Blocking have different technical definitions, in this context ([JS](http://w3bits.com/async-javascript/)), it means the same thing, that the script/resource won't stop execution, making the page load much faster.

**Comment by alexpflores** [comment] 2017-11-18 00:48
@kathreenriel This along with #273 and #276 can be closed/considered done. I've created #317 which is the output of these tasks, for your consideration in a future sprint.

**Comment by kathreenriel** [comment] 2017-11-18 01:29
Thx @alexpflores I'll tag these PWA issues and move them to Done

**Closed** 2018-10-23 19:49 UTC
Labels: Performance, SMALL - 1
