### ISSUE TITLE
Add more domains to the site (Ministry)

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#91] opened 2017-02-03 20:37 UTC
Was given a list of more authorized organizations by MInistry's ECE Registry. I'll generate the list and post it here

**Comment by paulagaube** [comment] 2018-06-19 22:45
As Northwest Community College is now known as Coast Mountain College, please replace "nwcc.bc.ca" with "coastmountaincollege.ca" as an approved domain on the Earlyyearsbc.ca and eypd.bccampus.ca sites.
(I don't think we need to keep "nwcc.bc.ca" because employees there will be using the new domain name.)

**Comment by bdolor** [comment] 2018-06-25 19:39
validate by domain plugin master branch has been updated and is live on prod. Paula is testing now.

**Comment by paulagaube** [comment] 2018-06-25 23:28
I was able to successfully create an test account ("pgaubeeditworks") with a domain name I added to the Validate by Domain plugin ("editworks.ca"), but the Role in the Profile is still "Subscriber" in this account and not "Editor" as expected. Sending this back to the Doing column.

(FYI, I did not receive the activation email so I manually Activated the account.)

**Comment by bdolor** [comment] 2018-06-26 17:05
The choice between Organizer and Learner was not marked as a required field as it is on the cert site. I updated production to make this a required field. 

If a user signs up as a Learner, they will be allocated to the 'Subscriber' role (option is in the dashboard, Settings -> General 'New User Default Role'). If they sign up as an organizer they will be allocated to the 'Editor' role (option is in Validate by Domain settings). 

Have confirmed this behaviour on cert and prod.

**Comment by kathreenriel** [comment] 2018-06-26 19:35
@paulagaube would you validate this in the role a potential Organizer

**Comment by kathreenriel** [comment] 2018-06-29 17:20
@paulagaube @alex-418 This plugin works for me. I added a telus.net domain name. Signed up as olive3 under kathreen@telus.net account, confirmed my account and was able to sign in as an Organizer and post events. I cannot replicate the problem. This issue appears to work as expected and I'm moving it to 'done'.

**Closed** 2018-06-29 22:49 UTC
Labels: Epic: Support Promotion of Pro.D, MEDIUM - 3

**Comment by paulagaube** [comment] 2018-07-05 17:04
Ok, all is well! Met with Brad this morning and he clarified how the Validate by Domain works. 

- For a user's account role to automatically change from "subscriber" to "editor", the Organizer must enter the Activation Key from the email they receive. This will change their role to Editor, as long as their  account includes a valid domain name. 
- If the account is "Pending" on the dashboard, and then an Administrator manually validates the user, the Admin has to manually change the role from Subscriber to Editor. (The role does not change to Editor automatically as the domain is not validated against the valid domain list.)

Also, so I have this information somewhere, after adding a new domain to the Valid Domain list, we need to update the list of valid organizations on the drop-down list on the Sign Up page too. Do that here:
Dashboard > Users > Profile Fields > Agency/Institution > Edit
