### ISSUE TITLE
Homepage: Revise Search by text section

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#293] opened 2017-11-07 23:14 UTC
- [ ] - Take out the locations search field
- [ ] - Move Start date and End date up
- [ ] - Add words "Search by" to  Start Date
- [ ] - Add words "Search by" to Category
- [ ] - Add the word "Community" to City/Community/Town
<img width="593" alt="search" src="https://user-images.githubusercontent.com/16693738/32522982-43776352-c3ce-11e7-9b80-98c5bd73c2ca.png">

**Comment by alexpflores** [comment] 2017-11-14 17:40
@kathreenriel Waiting for confirmation to remove location field

**Comment by kathreenriel** [comment] 2017-11-15 20:21
I think it is okay to take out the locations field. When I take a look at "User Searches" in the dashboard below is what is revealed. The additional fields "Within" and "Distance Units" do not appear on the production site. I think it best to keep off the site too.  
<img width="593" alt="screen shot 2017-11-15 at 12 16 37 pm" src="https://user-images.githubusercontent.com/16693738/32858132-3ef63542-c9ff-11e7-8e65-7c5939c8533d.png">

**Comment by alexpflores** [comment] 2017-11-16 00:51
Completed via #305, please standby for that to merge before validating.

**Comment by bdolor** [comment] 2017-11-16 21:20
I know it's not my role to validate, but I noticed this: 

![image](https://user-images.githubusercontent.com/2048170/32916425-e34f5250-cad0-11e7-9086-ca6fd3a0816d.png)

**Comment by kathreenriel** [comment] 2017-11-16 21:22
I'm looking at the results right now. Once a search has been completed this is the appearance of the homepage
<img width="881" alt="screen shot 2017-11-16 at 1 20 22 pm" src="https://user-images.githubusercontent.com/16693738/32916494-1ee9f1ee-cad1-11e7-91f7-dcb18b108830.png">

**Comment by bdolor** [comment] 2017-11-16 21:24
ack! I just needed to clear my cache for the homepage padding to go away, though I can recreate what you've posted above Kathreen. 

back to code I go.

**Comment by kathreenriel** [comment] 2017-11-16 21:25
Also, please put in the extra descriptions 
<img width="539" alt="screen shot 2017-11-16 at 1 23 37 pm" src="https://user-images.githubusercontent.com/16693738/32916614-869856e6-cad1-11e7-9f7b-cbcd22f2473e.png">

**Comment by kathreenriel** [comment] 2017-11-16 21:25
@bdolor feel free to hang out n the validation column!

**Comment by alexpflores** [comment] 2017-11-16 21:29
@kathreenriel What Browser please? @bdolor are you also seeing that order of fields on result page? It looks great on my local. 

@kathreenriel Looks like the default field text didn't update properly, probably typo somewhere. I can see the last field text should have definitely been updated, i'll fix.

**Comment by alexpflores** [comment] 2017-11-17 00:55
Also completed via #309, will be ready once that's approved/merged.

**Comment by alexpflores** [comment] 2017-11-17 18:25
This is also now ready for validation too!

**Comment by kathreenriel** [comment] 2017-11-17 19:12
<img width="539" alt="32916614-869856e6-cad1-11e7-9f7b-cbcd22f2473e" src="https://user-images.githubusercontent.com/16693738/32964437-21fae2f0-cb88-11e7-845e-97056055c1ef.png">

**Comment by kathreenriel** [comment] 2017-11-17 19:13
Missing the descriptions for the search field see above

**Comment by alexpflores** [comment] 2017-11-17 19:15
@kathreenriel Thanks Kathreen, looks like I'll have to update the version again so the field text gets updated... standby.

**Comment by kathreenriel** [comment] 2017-11-17 19:29
Just saw the update of the first field. Take out the first "Or" and lower case in second "or"  so that it states, "Search by Topic, Keyword or Location"

**Comment by alexpflores** [comment] 2017-11-17 19:59
cert/prod had a different field name than what my local had, which explains why they didn't update initially. Please see cert now.

**Comment by kathreenriel** [comment] 2017-11-17 20:28
Small thing - "or" instead of "Or" for or Location

**Comment by paulagaube** [comment] 2017-11-17 20:32
I'm popping in here quickly. Tested searching for "Vancouver" using just the text field "Search By Topic, Keyword Or Location" and four event results appeared (looks good). 
However, when I searched for Vancouver using the dropdown menu under "City/Community/Town" (and nothing else in any field), only one event result appeared. Why is there a difference? Is the text field a full-text search but the drop down "City/Community/Town" field is only based on exact location? 

I note that the three events in Vancouver that don't appear when the "Vancouver" drop-down search is chosen are for events in "Richmond" and "North Vancouver", and not just "Vancouver".

**Comment by alexpflores** [comment] 2017-11-17 20:37
@paulagaube That is correct. If you look at the results when you type they keyword "Vancouver" there's actually only one in Vancouver. Out of the four that show up, Two are in "North **Vancouver**" and the other one is in Richmond but at the "Radisson Hotel **Vancouver** Airport".

**Comment by alexpflores** [comment] 2017-11-17 20:41
@kathreenriel Interesting, there's some CSS styling that's transforming the `or` into `Or`.

**Comment by kathreenriel** [comment] 2017-11-17 20:49
Oh weird!!

**Comment by alexpflores** [comment] 2017-11-17 21:27
Should all look as expected now (clear browser cache for new styling to take effect to make the Or into or)

**Comment by kathreenriel** [comment] 2017-11-17 22:34
Yes! This was done!

**Comment by paulagaube** [comment] 2017-11-24 23:09
@kathreenriel I can confirm the search function works well, especially by location.

**Comment by kathreenriel** [comment] 2017-11-24 23:18
thanks @paulagaube

**Closed** 2018-10-23 19:54 UTC
Labels: SMALL - 1
