### ISSUE TITLE
Revise FAQs 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#515] opened 2018-08-16 21:19 UTC
### Description 

THe current Help needs to be updated both technically and in the content. **Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- EYPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by paulagaube** [comment] 2018-08-20 17:38
This is a duplicate of issue #350

**Comment by kathreenriel** [comment] 2018-08-31 22:46
@paulagaube looking at it on my iphone it renders really well I like the option of swiping down the topics without the extra text. There's no extra white space at the bottom on my phone

**Closed** 2018-10-18 16:02 UTC
Labels: non-dev
