### ISSUE TITLE
"Plan to attend" button should always be present

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#520] opened 2018-08-21 21:37 UTC
### Description

Not sure if this is a bug or not. Wanted to capture what I saw. 

On an Event page, the words "N/A leave blank" appear where the "Plan to Attend" button should be, just below the "Categories" and above "Target Audience". 

**Expected behaviour** 

Show the Plan to Attend button so I can add this to myEYPD as a Learner or Organizer.

### Steps to reproduce the problem

I noticed this on an event I had originally created some time ago. This event spanned multiple days, and the first days of the event was in the past. 

I duplicated the old event and updated the dates to the future. E.g., the button does not appear on this page: https://eypd.bccampus.ca/events/bugs-and-insects-part-4/

I created a couple NEW events with mostly the same information and the Plan to Attend button appeared:
https://eypd.bccampus.ca/events/diet-and-nutrition-level-1-2/
https://eypd.bccampus.ca/events/diet-and-nutrition-level-2/

This is what I see while logged in as a Learner:
![noplantoattend-bugs-insects4](https://user-images.githubusercontent.com/26391359/44430523-c58aaf80-a54f-11e8-9c07-bc27354aa761.png)

**Comment by alex-418** [comment] 2018-08-21 21:45
@paulagaube This is probably a symptom of brining this change in after this event was created. The "Plan to Attend" button is a feature of the Events Manager plugin that was disabled before.

**Comment by mandily-p** [comment] 2018-11-26 17:35
Notes from sprint planning: Will try to change the button behaviour to stay active until the end time of the event instead of the start. If that doesn't work, we'll change the messaging to the user.

**Comment by mandily-p** [comment] 2018-11-27 20:30
@kathreenriel Can you let us know what you would prefer here? 

1. Persistent button all of the time
-So the user can add the event to their myEYPD page at any point.

**Comment by mandily-p** [comment] 2018-11-27 23:00
Caution users with a modal confirmation if the event has already finished, "This event has happened in the past, are you sure you want to add to your events" options include "cancel" and "save event"

**Comment by kathreenriel** [comment] 2018-11-27 23:48
@mandily-p My understanding is as you have described and we discussed changing the title of the button  from "Plan To Attend" to "Save to myEYPD"

**Comment by brettjforsyth** [comment] 2018-11-28 00:53
@kathreenriel @mandily-p This page has a few default options that I would need to override to make this button show up all the time.
- Bookings not enable
- Available spaces 0
- event has started (which brings up the N/A message

Which of those needs to stay and what needs to go?

**Comment by kathreenriel** [comment] 2018-11-28 00:58
Stay:
Bookings not enable needs 

Available spaces and event has started...I"m not sure the effects of leaving those out or in.

**Comment by brettjforsyth** [comment] 2018-11-28 01:18
The button will not be shown when its full booked
event started is what is causing the N/A leave blank currently which is actually just a settable label

**Comment by brettjforsyth** [comment] 2018-11-28 14:56
@kathreenriel @mandily-p I have reworked this page so that the button shows after an event starts and shows the modal popup. Let me know if there are any visual changes needed before I submit the pull.
![screen shot 2018-11-28 at 9 50 52 am](https://user-images.githubusercontent.com/439832/49159790-40076000-f2f3-11e8-847b-d769ee6a0a49.png)

**Comment by mandily-p** [comment] 2018-11-29 08:16
Just curious - Did you ever find modals elsewhere on the site? I just had the thought that I'm not sure which pattern the site uses - Cancel first or second.

**Comment by paulagaube** [comment] 2018-12-01 00:00
@brettjforsyth @kathreenriel FYI, I just created a new event as an Organizer on CERT and inadvertently entered a date for the event that was in the past (January 2018). Since I couldn't see the event anymore as the Organizer (I can't see past events that I haven't planned to attend), I went in as an Administrator and changed the event's dates to 2019, as I had originally intended. Here is the event:

Event Name: Sand, Surf and Kelp: Understanding Ocean Tides 
Event ID: 1779
Event PostID: 4466

Then I went back to my Organizer account and saw the Event on my myEYPD page, but when went to the event details page, and want to click the "Plan to Attend" button, instead I see "N/A leave Blank". 

Since the event is now in the future, I believe the "Plan to Attend" button should still appear?

**Comment by kathreenriel** [comment] 2018-12-04 23:51
Tested this issue and found the following items to be corrected:

When a registered user (Organizer or Learner) opens an Event Description page and clicks on SavetomyEYPD a message appears that says, "Please Wait While The Booking Is Being Submitted" the message never disappears until the user clicks on "Save"
![bookings](https://user-images.githubusercontent.com/16693738/49480659-6a1dbe00-f7dc-11e8-953f-a6698e3bd2d3.jpg)

**Comment by brettjforsyth** [comment] 2018-12-05 15:18
@kathreenriel 
1) This seems to be functionality that has always been there. It is a JS alert message. We can remove it all together but not close it automatically.
2) Is this an issue or just needed clarity?
3) I am not sure what the issue is here? different style than expected?

**Comment by kathreenriel** [comment] 2018-12-05 16:23
@brettjforsyth 
1. Re: bookings I looked through the bookings settings to disable the message but couldn't see the option to remove it. Yes, I think the message should be removed. 
2. Re past dates and edits: I think this needs to be fixed. @paulagaube would like Organizers to see past events eventually so if an Organizer edits an event that includes a past date to a future date this message will appear. 
3. Re button style: The button style should be as it appears below and change when the cursor hovers over  or clicks on the button. 
<img width="175" alt="screen shot 2018-12-04 at 3 13 52 pm" src="https://user-images.githubusercontent.com/16693738/49527577-13a99180-f867-11e8-90df-f4c4cc20826e.png">

<img width="167" alt="style of button" src="https://user-images.githubusercontent.com/16693738/49527554-08566600-f867-11e8-8a59-bf951af80095.png">

**Comment by brettjforsyth** [comment] 2018-12-05 18:41
@kathreenriel can you check in the bookings/Registration section what the "Booking cut-off date" is set to for your events

**Comment by brettjforsyth** [comment] 2018-12-05 19:49
@kathreenriel 
1) I have created a new ticket to address this
2) I believe will be resolved with my above comment and is not a coding related issues.
3) @mandily-p create #597 which I think is the best place to capture all the work related to buttons

If this is all agreed upon I would like to move this back to validating.

**Comment by kathreenriel** [comment] 2018-12-06 20:17
Validated this issue in its original form at the top : N/A leave blank in place of "Place To Attend"  appears when events that began in the past and span to a date in the future 

Tested this on Chrome macbook. Added two events as an organizer that span a range of dates that start in the past and end in the future. 

SavetomyEYPD button appears and when clicked on expected message appears "This event has happened in the past, are you sure you want to add to your events?"

**Closed by kathreenriel** 2018-12-06 20:17 UTC
Labels: MEDIUM - 3

**Comment by paulagaube** [comment] 2018-12-06 20:20
@kathreenriel I have a couple questions about this issue that I have come across while validating. Can we discuss after lunch? I need a break.

**Comment by kathreenriel** [comment] 2018-12-06 20:22
Sure I'm on Skype let's chat when your ready
