### ISSUE TITLE
Wonky search fields after submitting search form

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#311] opened 2017-11-17 17:45 UTC
![wonky](https://user-images.githubusercontent.com/17072191/32961049-ebc408a8-cb7b-11e7-9046-9cbdacd3e883.png)

**Comment by kathreenriel** [comment] 2017-11-17 17:55
Oh this is weird..I just check the production site and this "wonky field" is happening there too. How on earth did I miss this?

**Comment by alexpflores** [comment] 2017-11-17 17:59
@kathreenriel Yes, I've also just noticed this isn't a side effect of anything we did this sprint. I'll do my best to try and find a fix.

**Comment by alexpflores** [comment] 2017-11-17 18:13
@kathreenriel Mystery deepens. It just magically fixed itself on my local, so I can't seem to replicate this on my local to try and find a fix :S... it looks fine now (chrome and safari). But I can still see the issue on eypd/prod. Perhaps it's an intermittent issue which is why it wasn't caught?

**Comment by kathreenriel** [comment] 2017-11-17 18:19
Grrr....I'm drinking more coffee than I should

**Comment by alexpflores** [comment] 2017-11-17 18:21
Sorry, brought this issue into this sprint thinking it was a quick fix and related to the changes i made! I'll put it in sprint backlog just in case @bdolor wants to take a stab at it this sprint :( sorry!

**Comment by kathreenriel** [comment] 2017-11-17 18:24
No problem. I didn't see this in prod. until today.

**Comment by alexpflores** [comment] 2017-11-29 00:43
@kathreenriel I've fixed this, but it'll still look a bit off because there's no title in the first search field. I've noticed that's the case in Prod and Cert as well, is this intentional? Or did I find another bug? 

Fixed: 
![screen shot 2017-11-28 at 3 37 34 pm](https://user-images.githubusercontent.com/17072191/33350261-b865a3a6-d452-11e7-8e54-7f8294b681aa.png)

Prod: 
![prod](https://user-images.githubusercontent.com/17072191/33350277-cba632fa-d452-11e7-9fcb-8d71721b0f5a.png)

**Comment by kathreenriel** [comment] 2017-11-29 17:02
@alexpflores I wonder if these fields are somehow connected to the fields on the homepage and they 'went wonky' when we omitted the location field in the search section of the homepage. Here's how I think the events result page appeared after a search

- results first 
- search fields
- there was no advanced search link
- there was no 'edit this entry' link at the bottom of the page 
![search](https://user-images.githubusercontent.com/16693738/33388171-0bdaed7a-d4e4-11e7-8130-7ad5c77fcd2b.jpg)

**Comment by kathreenriel** [comment] 2017-11-29 19:18
Yes, I'm certain that the search results page had the listing results (or not results) first then the fields below (as illustrated in my last posted fantastic illustration :)

**Comment by alexpflores** [comment] 2017-11-29 19:19
@kathreenriel Okay, thank you :) I will make that happen.

**Comment by paulagaube** [comment] 2017-11-29 21:32
I had a couples thoughts. How about copying the format on the home page, which is like: 
           Title Text<br /> 
           [search box]
Then we could add the text "Search by Topic, Keyword or Location" above the first field?
Like this:
![stacked](https://user-images.githubusercontent.com/26391359/33400086-a5b7ffda-d509-11e7-850a-502f80d1a229.png)

**Comment by paulagaube** [comment] 2017-11-29 22:14
See also the Contact Us page, which stacks the search box under the text title: https://eypd.bccampus.ca/contact-us/

**Comment by alexpflores** [comment] 2017-11-29 23:07
@kathreenriel Got it all sorted except moving the search below the results. I've confirmed it's the default setting controlled by the Events Manager plugin, please see screenshot of settings page: 

![settings](https://user-images.githubusercontent.com/17072191/33402763-75eb069a-d512-11e7-8dd9-fdbec1ec3e28.png)

To move the search below the results, unfortunately it wouldn't be a quick task. I'd like to suggest moving this into it's own Card, and perhaps even leaving it on top of the results. When I think of search, I can say most such as google/bing etc behave in this way. 

If you want to go ahead and move it,  here's some details for the new issue: 
The position is controlled by `function em_content($page_content)` inside of `em-events.php` which is not something we can bring into our EYPD theme to override the position of the search. This will likely require overriding via a filter.

**Comment by kathreenriel** [comment] 2017-11-29 23:19
I appreciate looking into this @alexpflores Wow..I'm sure the search fields were positioned under the search results until recently. However given the choice of leaving it the way it is or Show events search or leaving it out.. I'm leaning toward selecting "no" for this option. I think about it a little more

**Comment by alexpflores** [comment] 2017-11-30 00:00
@kathreenriel Completed via #326 no more wobbly fields

**Comment by kathreenriel** [comment] 2017-11-30 17:37
Okay

**Comment by paulagaube** [comment] 2017-11-30 18:23
The search fields and Event listings looks good to me in I.E. 11 (and is the same layout as the home page search fields):
![2017-11-30-ie11-searchevents](https://user-images.githubusercontent.com/26391359/33447456-3ad0c5c6-d5b8-11e7-825e-f00ccb49b06e.png)

**Comment by kathreenriel** [comment] 2017-11-30 19:10
okay thanks @paulagaube

**Closed** 2018-04-18 16:51 UTC
Labels: MEDIUM - 3
