### ISSUE TITLE
Events Export

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#570] opened 2018-11-19 20:13 UTC
**Description of Current Status**
The export function for events exports all past and future event data on prod from the Dashboard-myEYPD - Export to Excel. When an administrator clicks on Export to Excel the following information is created in a Spreadsheet: 

- Event Title	
- Owner	
- Status	
- Published date	
- Start date	
- End date
- Start time	
- End time	
- Presenter	
- Registration Contact E-mail	
- Location ID	
- Event ID

**User Story:** 

As an administrator I need to see more information in order to fix errors in duplicate locations and analyze data related to how events are distributed throughout B.C. over a given time period 

**Suggested Revision**  
Revise the plugin to add the following data columns to the export:

- Event Cost
- Professional Certificate hours
- Event Location Name  (as in, City)
- Event Category/ies
- Event Page Link
- Event Location Link (example:  https://earlyyearsbc.ca/locations/bc-childrens-hospital-chan-centre-for-family-health-education/)

Measures of Success

The Export feature is available in the Dashboard - myEYPD and allows administrators to download all the information it currently exports and six additional columns of information 
- Event Title	
- Owner	
- Status	
- Published date	
- Start date	
- End date
- Start time	
- End time	
- Presenter	
- Registration Contact E-mail	
- Location ID	
- Event ID
- Cost
- Certificate hours
- Event Location Name (City or Town)
- Event Category/ies
- Event Page Link
- Event Location Link

Version
WP 4.9.7

**Comment by bdolor** [comment] 2018-11-26 18:46
requires a conversation about the text blob that are attributes

**Comment by kathreenriel** [comment] 2018-11-29 20:13
@bdolor @paulagaube and @kkilbey have discussed prioritizing all the text 'blobs' We're thinking we want to see it all and what it looks like in an export then determine how we can organize it and/or what we may need to do next to make sense of it all. Please proceed with the export as described above. Ready, aim, fire! and we'll deal...

**Comment by kathreenriel** [comment] 2019-01-14 21:54
On my first review there appears to a duplication of events. 
<img width="1170" alt="duplicate" src="https://user-images.githubusercontent.com/16693738/51143668-e0fa9d80-1803-11e9-91fa-f237207f2f70.png">

**Comment by kathreenriel** [comment] 2019-01-14 21:55
@paulagaube would you take a look at this export issue too.

**Comment by bdolor** [comment] 2019-01-14 22:06
ah, one repetition per category...okay I see the problem.

**Comment by paulagaube** [comment] 2019-01-14 23:58
**I am still looking and testing:**
Dashboard > Tools > Excel Export > Export Users (click "Include personally identifiable information in export") - This works as expected for me. 

Dashboard > Tools > Excel Export > Export Post Types > _choose drop-down list item_ > Export
**post** 
**page**
**attachment**
**features**
**forum**
**topic**
**reply**
**location** - still looking at this. 
**event**
**bp_doc**
**faq**
**events and location** -  confirmed there is a big blob of attributes in column under title "Event Attributes".

**Comment by bdolor** [comment] 2019-01-15 19:40
updates have been merged

**Comment by kathreenriel** [comment] 2019-01-15 19:59
@bdolor @alex-418 There are several errors with the exported date

1. There are still duplicate events
2. Missing event attribute information (see green highlighted sections)
3. Partial attribute information (see orange highlighted sections) 
[errors.xlsx](https://github.com/BCcampus/eypd/files/2761216/errors.xlsx)

**Comment by bdolor** [comment] 2019-01-15 20:01
Kathreen, there was a delay in the build (service timeout) - I just checked and it works as expected...please export again.

**Comment by kathreenriel** [comment] 2019-01-15 20:04
Okay will check again

**Comment by kathreenriel** [comment] 2019-01-15 21:53
There still seem to be blanks in the Event attributes column. It appears to occur for events after November 15, 2017 (according to @paulagaube observation)

[blanks-see yello.xlsx](https://github.com/BCcampus/eypd/files/2761617/blanks-see.yello.xlsx)

**Comment by bdolor** [comment] 2019-01-15 21:59
okay, I see that too...and gather it's related to the data structure for attributes changing. Will address gathering event attributes from the new _and_ old data structure.

**Comment by kathreenriel** [comment] 2019-01-16 19:45
I checked this and the 8 blanks that appear in the event attributes are indeed blank in the event descriptions. I don't see any disparities between the event descriptions and the export. @paulagaube would you confirm?

**Comment by kathreenriel** [comment] 2019-01-16 20:21
Just exported data for topics and replies super stoked about getting the summary of users who are active in this forum.

**Comment by paulagaube** [comment] 2019-01-16 23:57
@kathreenriel @bdolor this looks really promising. I want to do a couple tests tomorrow on this. I ran out of time today.

**Comment by paulagaube** [comment] 2019-01-18 00:03
Still trying to figure out a workflow for identifying and correcting duplicate locations using the exported spreadsheets. 
I gave Dave S a copy of the events and location spreadsheet so he could inspect the blob. :)

**Comment by kathreenriel** [comment] 2019-01-18 20:18
Dave S reviewed with @paulagaube @kkilbey  and a formula for extracting the data from the Events Attribute column. 
Manually moving the Events location (column J) and Events Link (column K) beside Column A Events ID is one way of finding duplicate event locations but does not clearly identify original event location from its duplicate. The original process for finding duplicate locations may still be the most reliable method for eliminating erroneous duplicate locations. 
This is validation of how the export feature currently works is complete.

**Comment by paulagaube** [comment] 2019-01-21 20:05
Confirmed this Events Export tool is on Prod and working as expected. Moving to Done on Prod.

**Comment by alex-418** [comment] 2019-05-21 22:21
Thank you @dshaykewich for articulating the problem to solve: `Identify which events are using duplicate or redundant locations, like the six different "University of Victoria" locations.` To solve this, I've added the `location slug` column to the `events and locations` export via https://github.com/BCcampus/eypd/commit/34c345e8df7532a1ba88a5658668e02d9a74b12b. 

This allows us to see these redundant locations because each slug is unique. Please see screenshot below:

![location_slug](https://user-images.githubusercontent.com/17072191/58134193-dd748a00-7bda-11e9-940b-037122cb772a.png)

**Comment by dshaykewich** [comment] 2019-05-21 22:36
Thanks @alex-418 !

**Comment by kathreenriel** [comment] 2019-05-21 23:15
This could potentially save a lot of time we've spent in tracking down duplicate locations @paulagaube what do you think?

**Comment by paulagaube** [comment] 2019-05-21 23:25
I'm excited to look closely at this tomorrow! My hope is that this additional field will solve the problem I've had tracking down these duplicate locations and the events they are associated with.

**Comment by alex-418** [comment] 2019-05-22 16:36
Add city and state to export.

**Comment by alex-418** [comment] 2019-05-22 20:37
Completed via https://github.com/BCcampus/eypd/commit/bccf00f926619ff868c53910c3efec1192d1e205 

Here's a screenshot: 
![province_city](https://user-images.githubusercontent.com/17072191/58207013-b5e2f780-7c96-11e9-9fc6-c045738e2559.png)

**Comment by dshaykewich** [comment] 2019-05-22 20:39
@paulagaube , looks like there's also an opportunity to reconcile the BC/British Columbia duplicates.

**Comment by kathreenriel** [comment] 2019-05-23 19:27
This shows the city and province as requested. This will have a significant impact on the way we can find duplicates, and look for geographic patterns in training events that are posted.

**Comment by kathreenriel** [comment] 2019-05-24 18:09
This works on Prod. Never thought i would be excited about a spreadsheet :)

**Closed** 2019-05-31 20:03 UTC
Labels: MEDIUM - 3
